# Generated by Django 6.0.7 on 2026-07-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=30)),
                ('autor_livro', models.CharField(max_length=30)),
                ('ano_publicacao', models.IntegerField()),
                ('nota_livro', models.FloatField()),
                ('obs_livro', models.CharField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
    ]
