# Generated by Django 6.0.7 on 2026-07-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livroApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nota_livro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='obs_livro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
